import { Knex } from 'knex';

/**
 * Seed: Datos Mock para Desarrollo
 * 
 * Pobla las tablas mock con datos de ejemplo (6+ elementos de cada tipo).
 * Estos datos permiten desarrollar componentes sin necesidad de datos reales.
 */

export async function seed(knex: Knex): Promise<void> {
  // Obtener el primer tenant (asumiendo que existe al menos uno)
  const tenant = await knex('tenants').first();
  if (!tenant) {
    console.log('⚠️ No hay tenants en la base de datos. Skipping mock data seed.');
    return;
  }

  const tenantId = tenant.id;

  // Limpiar datos existentes (opcional, solo si queremos resetear)
  // await knex('mock_asesores').where('tenant_id', tenantId).del();
  // await knex('mock_faqs').where('tenant_id', tenantId).del();
  // await knex('mock_testimonios').where('tenant_id', tenantId).del();
  // await knex('mock_articulos').where('tenant_id', tenantId).del();
  // await knex('mock_videos').where('tenant_id', tenantId).del();
  // await knex('mock_textos_sueltos').where('tenant_id', tenantId).del();
  // await knex('mock_carruseles_propiedades').where('tenant_id', tenantId).del();
  // await knex('mock_categorias_contenido').where('tenant_id', tenantId).del();
  // await knex('mock_stats').where('tenant_id', tenantId).del();

  // 1. Stats
  await knex('mock_stats').insert({
    tenant_id: tenantId,
    data: JSON.stringify({
      total_propiedades: 245,
      propiedades_activas: 189,
      propiedades_vendidas_mes: 12,
      propiedades_alquiladas_mes: 8,
      clientes_activos: 156,
      valor_total_inventario: 45000000,
      promedio_venta: 285000,
      tiempo_promedio_venta: 45,
    }),
  });

  // 2. Categorías de Videos (6 categorías)
  const categoriasVideos = await knex('mock_categorias_contenido').insert([
    {
      tenant_id: tenantId,
      tipo_contenido: 'videos',
      nombre: 'Tours Virtuales',
      slug: 'tours-virtuales',
      descripcion: 'Recorridos virtuales de nuestras propiedades',
      icono: '🎥',
      numero_elementos: 24,
      metadata: JSON.stringify({ color: '#3b82f6', orden: 1 }),
      traducciones: JSON.stringify({
        en: { nombre: 'Virtual Tours', descripcion: 'Virtual tours of our properties' },
        fr: { nombre: 'Visites Virtuelles', descripcion: 'Visites virtuelles de nos propriétés' },
      }),
      activa: true,
      orden: 1,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'videos',
      nombre: 'Consejos de Inversión',
      slug: 'consejos-inversion',
      descripcion: 'Tips y estrategias para invertir en bienes raíces',
      icono: '💼',
      numero_elementos: 18,
      metadata: JSON.stringify({ color: '#10b981', orden: 2 }),
      traducciones: JSON.stringify({
        en: { nombre: 'Investment Tips', descripcion: 'Tips and strategies for real estate investment' },
      }),
      activa: true,
      orden: 2,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'videos',
      nombre: 'Lanzamientos',
      slug: 'lanzamientos',
      descripcion: 'Nuevos proyectos y lanzamientos exclusivos',
      icono: '🏗️',
      numero_elementos: 12,
      metadata: JSON.stringify({ color: '#f59e0b', orden: 3 }),
      activa: true,
      orden: 3,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'videos',
      nombre: 'Testimonios en Video',
      slug: 'testimonios-video',
      descripcion: 'Experiencias de nuestros clientes',
      icono: '👥',
      numero_elementos: 15,
      metadata: JSON.stringify({ color: '#8b5cf6', orden: 4 }),
      activa: true,
      orden: 4,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'videos',
      nombre: 'Market Updates',
      slug: 'market-updates',
      descripcion: 'Actualizaciones del mercado inmobiliario',
      icono: '📊',
      numero_elementos: 9,
      metadata: JSON.stringify({ color: '#ec4899', orden: 5 }),
      activa: true,
      orden: 5,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'videos',
      nombre: 'Zonas y Ubicaciones',
      slug: 'zonas-ubicaciones',
      descripcion: 'Explora las mejores zonas y ubicaciones',
      icono: '📍',
      numero_elementos: 21,
      metadata: JSON.stringify({ color: '#06b6d4', orden: 6 }),
      activa: true,
      orden: 6,
    },
  ]).returning('id');

  // 3. Categorías de Artículos (6 categorías)
  const categoriasArticulos = await knex('mock_categorias_contenido').insert([
    {
      tenant_id: tenantId,
      tipo_contenido: 'articulos',
      nombre: 'Tendencias del Mercado',
      slug: 'tendencias-mercado',
      descripcion: 'Últimas tendencias en el mercado inmobiliario',
      icono: '📈',
      numero_elementos: 32,
      metadata: JSON.stringify({ color: '#3b82f6', orden: 1 }),
      activa: true,
      orden: 1,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'articulos',
      nombre: 'Guías de Compra',
      slug: 'guias-compra',
      descripcion: 'Guías completas para comprar tu propiedad',
      icono: '📖',
      numero_elementos: 28,
      metadata: JSON.stringify({ color: '#10b981', orden: 2 }),
      activa: true,
      orden: 2,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'articulos',
      nombre: 'Consejos para Vendedores',
      slug: 'consejos-vendedores',
      descripcion: 'Tips para vender tu propiedad más rápido',
      icono: '💡',
      numero_elementos: 19,
      metadata: JSON.stringify({ color: '#f59e0b', orden: 3 }),
      activa: true,
      orden: 3,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'articulos',
      nombre: 'Diseño y Decoración',
      slug: 'diseno-decoracion',
      descripcion: 'Ideas de diseño y decoración para tu hogar',
      icono: '🎨',
      numero_elementos: 24,
      metadata: JSON.stringify({ color: '#8b5cf6', orden: 4 }),
      activa: true,
      orden: 4,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'articulos',
      nombre: 'Noticias',
      slug: 'noticias',
      descripcion: 'Noticias relevantes del sector inmobiliario',
      icono: '📰',
      numero_elementos: 15,
      metadata: JSON.stringify({ color: '#ec4899', orden: 5 }),
      activa: true,
      orden: 5,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'articulos',
      nombre: 'Lifestyle',
      slug: 'lifestyle',
      descripcion: 'Estilo de vida y experiencias',
      icono: '✨',
      numero_elementos: 11,
      metadata: JSON.stringify({ color: '#06b6d4', orden: 6 }),
      activa: true,
      orden: 6,
    },
  ]).returning('id');

  // 4. Categorías de Testimonios (6 categorías)
  const categoriasTestimonios = await knex('mock_categorias_contenido').insert([
    {
      tenant_id: tenantId,
      tipo_contenido: 'testimonios',
      nombre: 'Ventas Exitosas',
      slug: 'ventas-exitosas',
      descripcion: 'Testimonios de clientes que compraron con nosotros',
      icono: '🏠',
      numero_elementos: 42,
      metadata: JSON.stringify({ color: '#10b981', orden: 1 }),
      activa: true,
      orden: 1,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'testimonios',
      nombre: 'Alquileres',
      slug: 'alquileres',
      descripcion: 'Experiencias de nuestros arrendatarios',
      icono: '🔑',
      numero_elementos: 38,
      metadata: JSON.stringify({ color: '#3b82f6', orden: 2 }),
      activa: true,
      orden: 2,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'testimonios',
      nombre: 'Inversiones',
      slug: 'inversiones',
      descripcion: 'Testimonios de inversionistas satisfechos',
      icono: '💰',
      numero_elementos: 29,
      metadata: JSON.stringify({ color: '#f59e0b', orden: 3 }),
      activa: true,
      orden: 3,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'testimonios',
      nombre: 'Proyectos Nuevos',
      slug: 'proyectos-nuevos',
      descripcion: 'Testimonios de compradores de proyectos nuevos',
      icono: '🏗️',
      numero_elementos: 31,
      metadata: JSON.stringify({ color: '#8b5cf6', orden: 4 }),
      activa: true,
      orden: 4,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'testimonios',
      nombre: 'Servicio al Cliente',
      slug: 'servicio-cliente',
      descripcion: 'Testimonios sobre nuestro excelente servicio',
      icono: '⭐',
      numero_elementos: 35,
      metadata: JSON.stringify({ color: '#ec4899', orden: 5 }),
      activa: true,
      orden: 5,
    },
    {
      tenant_id: tenantId,
      tipo_contenido: 'testimonios',
      nombre: 'Lujo y Premium',
      slug: 'lujo-premium',
      descripcion: 'Testimonios de propiedades de lujo',
      icono: '💎',
      numero_elementos: 18,
      metadata: JSON.stringify({ color: '#06b6d4', orden: 6 }),
      activa: true,
      orden: 6,
    },
  ]).returning('id');

  const categoriaVideo1 = categoriasVideos[0].id;
  const categoriaArticulo1 = categoriasArticulos[0].id;
  const categoriaTestimonio1 = categoriasTestimonios[0].id;

  // 5. Videos (8 videos)
  await knex('mock_videos').insert([
    {
      tenant_id: tenantId,
      titulo: 'Tour Virtual: Apartamento de Lujo en Zona Premium',
      descripcion: 'Descubre este espectacular apartamento de 3 habitaciones con vista al mar',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800',
      duracion: '05:32',
      categoria_id: categoriaVideo1,
      metadata: JSON.stringify({ tipo: 'tour_virtual', propiedad_id: null }),
      activo: true,
      vistas: 1245,
      fecha_publicacion: new Date('2024-01-15'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Cómo Invertir en Bienes Raíces en 2024',
      descripcion: 'Guía completa para inversionistas principiantes',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
      duracion: '12:45',
      categoria_id: categoriasVideos[1].id,
      metadata: JSON.stringify({ tipo: 'educativo' }),
      activo: true,
      vistas: 3421,
      fecha_publicacion: new Date('2024-02-01'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Lanzamiento: Residencial Las Palmas',
      descripcion: 'Conoce nuestro nuevo proyecto residencial exclusivo',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      duracion: '08:15',
      categoria_id: categoriasVideos[2].id,
      metadata: JSON.stringify({ tipo: 'lanzamiento', proyecto_id: 'proyecto-123' }),
      activo: true,
      vistas: 2890,
      fecha_publicacion: new Date('2024-02-10'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Testimonio: María y su Nueva Casa',
      descripcion: 'Escucha la experiencia de María al comprar su casa soñada',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800',
      duracion: '04:20',
      categoria_id: categoriasVideos[3].id,
      metadata: JSON.stringify({ tipo: 'testimonio' }),
      activo: true,
      vistas: 1567,
      fecha_publicacion: new Date('2024-01-20'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Market Update Q1 2024: Tendencias y Proyecciones',
      descripcion: 'Análisis del mercado inmobiliario del primer trimestre',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
      duracion: '15:30',
      categoria_id: categoriasVideos[4].id,
      metadata: JSON.stringify({ tipo: 'market_update', trimestre: 'Q1', año: 2024 }),
      activo: true,
      vistas: 2100,
      fecha_publicacion: new Date('2024-03-01'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Explorando la Zona Norte: Guía Completa',
      descripcion: 'Todo lo que necesitas saber sobre vivir en la Zona Norte',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      duracion: '10:45',
      categoria_id: categoriasVideos[5].id,
      metadata: JSON.stringify({ tipo: 'guia_zona', zona: 'norte' }),
      activo: true,
      vistas: 1876,
      fecha_publicacion: new Date('2024-02-15'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Tour 360°: Villa con Piscina y Jardín',
      descripcion: 'Experiencia inmersiva de esta increíble villa',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      duracion: '06:58',
      categoria_id: categoriaVideo1,
      metadata: JSON.stringify({ tipo: 'tour_360', propiedad_id: null }),
      activo: true,
      vistas: 2345,
      fecha_publicacion: new Date('2024-01-25'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Estrategias de Negociación en Inmuebles',
      descripcion: 'Aprende las mejores técnicas para negociar tu próxima propiedad',
      url_video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
      duracion: '11:22',
      categoria_id: categoriasVideos[1].id,
      metadata: JSON.stringify({ tipo: 'educativo' }),
      activo: true,
      vistas: 3124,
      fecha_publicacion: new Date('2024-02-05'),
    },
  ]);

  // 6. Artículos (8 artículos)
  await knex('mock_articulos').insert([
    {
      tenant_id: tenantId,
      titulo: '5 Razones para Invertir en Bienes Raíces en 2024',
      resumen: 'El mercado inmobiliario presenta oportunidades únicas este año. Descubre por qué es el momento ideal para invertir.',
      contenido: '<p>El mercado inmobiliario está experimentando cambios significativos que presentan oportunidades excelentes para inversionistas...</p>',
      autor: 'Equipo CLIC',
      thumbnail_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
      categoria_id: categoriaArticulo1,
      tags: JSON.stringify(['inversion', 'bienes-raices', '2024']),
      activo: true,
      publicado: true,
      vistas: 3421,
      fecha_publicacion: new Date('2024-01-10'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Guía Completa: Cómo Comprar tu Primera Propiedad',
      resumen: 'Todo lo que necesitas saber antes de dar el gran paso de comprar tu primera propiedad.',
      contenido: '<p>Comprar tu primera propiedad es un hito importante en la vida. Esta guía te acompañará en cada paso del proceso...</p>',
      autor: 'Ana Martínez',
      thumbnail_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
      categoria_id: categoriasArticulos[1].id,
      tags: JSON.stringify(['guia', 'primera-propiedad', 'comprar']),
      activo: true,
      publicado: true,
      vistas: 5123,
      fecha_publicacion: new Date('2024-01-05'),
    },
    {
      tenant_id: tenantId,
      titulo: '10 Tips para Vender tu Propiedad Más Rápido',
      resumen: 'Consejos prácticos para preparar tu propiedad y conseguir una venta rápida y exitosa.',
      contenido: '<p>Vender una propiedad puede ser un proceso largo, pero con los consejos correctos puedes acelerarlo significativamente...</p>',
      autor: 'Carlos Rodríguez',
      thumbnail_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
      categoria_id: categoriasArticulos[2].id,
      tags: JSON.stringify(['vender', 'tips', 'rapido']),
      activo: true,
      publicado: true,
      vistas: 4287,
      fecha_publicacion: new Date('2024-01-18'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Tendencias de Decoración 2024: Estilos que Definen el Año',
      resumen: 'Descubre las últimas tendencias en diseño de interiores que están marcando el 2024.',
      contenido: '<p>El 2024 trae consigo nuevas tendencias en decoración que combinan funcionalidad, sostenibilidad y estilo...</p>',
      autor: 'Laura Sánchez',
      thumbnail_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
      categoria_id: categoriasArticulos[3].id,
      tags: JSON.stringify(['decoracion', 'tendencias', '2024']),
      activo: true,
      publicado: true,
      vistas: 3892,
      fecha_publicacion: new Date('2024-01-12'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Nuevas Normativas de Zonificación Afectan al Sector',
      resumen: 'Conoce cómo las nuevas normativas impactan en el desarrollo inmobiliario.',
      contenido: '<p>El gobierno ha anunciado cambios importantes en las normativas de zonificación que afectarán a varios proyectos...</p>',
      autor: 'Equipo CLIC',
      thumbnail_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
      categoria_id: categoriasArticulos[4].id,
      tags: JSON.stringify(['noticias', 'normativas', 'sector']),
      activo: true,
      publicado: true,
      vistas: 2156,
      fecha_publicacion: new Date('2024-02-08'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Living la Vida: Estilo de Vida en Residencias Premium',
      resumen: 'Explora cómo el estilo de vida moderno se integra en las residencias de lujo.',
      contenido: '<p>Las residencias premium de hoy en día van más allá de simples espacios habitacionales...</p>',
      autor: 'María González',
      thumbnail_url: 'https://images.unsplash.com/photo-1560448075-cbc16bb4af90?w=800',
      categoria_id: categoriasArticulos[5].id,
      tags: JSON.stringify(['lifestyle', 'lujo', 'residencias']),
      activo: true,
      publicado: true,
      vistas: 1876,
      fecha_publicacion: new Date('2024-01-28'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Análisis de Mercado: Proyecciones para el Segundo Semestre',
      resumen: 'Expertos analizan las tendencias y proyecciones del mercado inmobiliario.',
      contenido: '<p>El segundo semestre de 2024 se presenta con cambios interesantes en el sector inmobiliario...</p>',
      autor: 'Equipo CLIC',
      thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
      categoria_id: categoriaArticulo1,
      tags: JSON.stringify(['analisis', 'mercado', 'proyecciones']),
      activo: true,
      publicado: true,
      vistas: 2987,
      fecha_publicacion: new Date('2024-02-12'),
    },
    {
      tenant_id: tenantId,
      titulo: 'Todo sobre Hipotecas: Guía para Principiantes',
      resumen: 'Entiende todo lo necesario sobre hipotecas antes de solicitar una.',
      contenido: '<p>Obtener una hipoteca puede ser complicado si no entiendes el proceso. Esta guía te ayudará...</p>',
      autor: 'Roberto Pérez',
      thumbnail_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
      categoria_id: categoriasArticulos[1].id,
      tags: JSON.stringify(['hipotecas', 'guia', 'financiamiento']),
      activo: true,
      publicado: true,
      vistas: 4231,
      fecha_publicacion: new Date('2024-01-22'),
    },
  ]);

  // 7. Testimonios (8 testimonios)
  await knex('mock_testimonios').insert([
    {
      tenant_id: tenantId,
      nombre_cliente: 'Juan Pérez',
      ubicacion: 'Santo Domingo Este',
      testimonio: 'Excelente servicio. El equipo de CLIC me ayudó a encontrar el apartamento perfecto en tiempo récord. Muy profesionales y atentos a todos los detalles.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=1',
      tipo_propiedad: 'Apartamento',
      categoria_id: categoriaTestimonio1,
      activo: true,
      destacado: true,
      fecha: new Date('2024-01-15'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'María García',
      ubicacion: 'Punta Cana',
      testimonio: 'Alquilamos un apartamento para vacaciones y quedamos encantados. Todo el proceso fue muy sencillo y la propiedad superó nuestras expectativas.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=5',
      tipo_propiedad: 'Apartamento',
      categoria_id: categoriasTestimonios[1].id,
      activo: true,
      destacado: true,
      fecha: new Date('2024-01-20'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'Carlos Rodríguez',
      ubicacion: 'Santiago',
      testimonio: 'Como inversionista, confío completamente en CLIC. Me han ayudado a construir un portafolio sólido de propiedades rentables.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=12',
      tipo_propiedad: 'Múltiples',
      categoria_id: categoriasTestimonios[2].id,
      activo: true,
      destacado: false,
      fecha: new Date('2024-01-25'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'Ana Martínez',
      ubicacion: 'La Romana',
      testimonio: 'Compramos un apartamento en el proyecto Residencial Las Palmas y estamos muy contentos. El proceso fue transparente y profesional.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=9',
      tipo_propiedad: 'Apartamento',
      categoria_id: categoriasTestimonios[3].id,
      activo: true,
      destacado: true,
      fecha: new Date('2024-02-01'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'Luis Hernández',
      ubicacion: 'Santo Domingo',
      testimonio: 'El servicio al cliente de CLIC es excepcional. Siempre están disponibles para resolver cualquier duda o problema. Altamente recomendado.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=33',
      tipo_propiedad: 'Casa',
      categoria_id: categoriasTestimonios[4].id,
      activo: true,
      destacado: false,
      fecha: new Date('2024-02-05'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'Sofía López',
      ubicacion: 'Bávaro',
      testimonio: 'Adquirimos una villa de lujo y el servicio fue impecable desde el primer día. CLIC realmente entiende el mercado premium.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=47',
      tipo_propiedad: 'Villa',
      categoria_id: categoriasTestimonios[5].id,
      activo: true,
      destacado: true,
      fecha: new Date('2024-02-10'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'Pedro González',
      ubicacion: 'Puerto Plata',
      testimonio: 'Vendimos nuestra propiedad en tiempo récord gracias a la estrategia de marketing de CLIC. Excelente trabajo del equipo.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=52',
      tipo_propiedad: 'Casa',
      categoria_id: categoriaTestimonio1,
      activo: true,
      destacado: false,
      fecha: new Date('2024-02-12'),
    },
    {
      tenant_id: tenantId,
      nombre_cliente: 'Isabel Ramírez',
      ubicacion: 'Santo Domingo Norte',
      testimonio: 'Buscábamos un apartamento para alquilar y CLIC nos encontró exactamente lo que necesitábamos. Muy recomendados.',
      calificacion: 5,
      foto_url: 'https://i.pravatar.cc/150?img=68',
      tipo_propiedad: 'Apartamento',
      categoria_id: categoriasTestimonios[1].id,
      activo: true,
      destacado: false,
      fecha: new Date('2024-02-15'),
    },
  ]);

  // 8. FAQs (8 FAQs)
  await knex('mock_faqs').insert([
    {
      tenant_id: tenantId,
      pregunta: '¿Cómo puedo empezar a buscar una propiedad?',
      respuesta: 'Puedes comenzar explorando nuestro catálogo online, usar nuestros filtros de búsqueda avanzados, o contactar directamente con uno de nuestros asesores que te guiará en todo el proceso.',
      categoria: 'general',
      orden: 1,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Qué documentos necesito para comprar una propiedad?',
      respuesta: 'Los documentos principales incluyen: identificación oficial, comprobante de ingresos, referencias bancarias, y en algunos casos, aval. Nuestro equipo te guiará con todos los requisitos específicos.',
      categoria: 'compra',
      orden: 2,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Ofrecen financiamiento o hipotecas?',
      respuesta: 'Sí, trabajamos con varios bancos e instituciones financieras para ayudarte a obtener el mejor financiamiento posible. Nuestro equipo te ayudará a evaluar tus opciones.',
      categoria: 'financiamiento',
      orden: 3,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Cuánto tiempo toma el proceso de compra?',
      respuesta: 'El tiempo varía según el tipo de propiedad y la complejidad de la transacción. En promedio, el proceso completo puede tomar entre 30 a 60 días hábiles.',
      categoria: 'proceso',
      orden: 4,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Puedo visitar las propiedades antes de comprar?',
      respuesta: '¡Por supuesto! Ofrecemos visitas programadas a todas nuestras propiedades. También tenemos tours virtuales disponibles para propiedades seleccionadas.',
      categoria: 'visitas',
      orden: 5,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Qué comisiones cobran por sus servicios?',
      respuesta: 'Nuestras comisiones varían según el tipo de servicio (compra, venta, alquiler). Te proporcionaremos información detallada y transparente antes de iniciar cualquier proceso.',
      categoria: 'costos',
      orden: 6,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Trabajan con propiedades de alquiler vacacional?',
      respuesta: 'Sí, tenemos una amplia selección de propiedades disponibles para alquiler vacacional, especialmente en zonas turísticas. Puedes filtrar por este tipo en nuestra plataforma.',
      categoria: 'alquiler',
      orden: 7,
      activo: true,
    },
    {
      tenant_id: tenantId,
      pregunta: '¿Ofrecen servicios de gestión de propiedades?',
      respuesta: 'Sí, ofrecemos servicios completos de gestión de propiedades que incluyen mantenimiento, alquiler, cobro de rentas, y más. Contáctanos para conocer todos nuestros servicios.',
      categoria: 'gestion',
      orden: 8,
      activo: true,
    },
  ]);

  // 9. Carruseles de Propiedades (6 carruseles temáticos)
  await knex('mock_carruseles_propiedades').insert([
    {
      tenant_id: tenantId,
      nombre: 'Perfectos para Airbnb',
      slug: 'perfectos-airbnb',
      configuracion: JSON.stringify({
        intencion: 'alquiler',
        tags: ['airbnb', 'rentable', 'turismo'],
        caracteristicas: ['amueblado', 'wifi', 'aire-acondicionado'],
        precio_max: 5000,
        ubicacion_tipo: 'zona-turistica',
        rentabilidad_minima: 8,
      }),
      propiedades_ids: JSON.stringify([]),
      activo: true,
    },
    {
      tenant_id: tenantId,
      nombre: 'Todo Lujo',
      slug: 'todo-lujo',
      configuracion: JSON.stringify({
        categoria: 'lujo',
        precio_min: 500000,
        caracteristicas: ['piscina', 'jacuzzi', 'gimnasio', 'concierge'],
        zonas: ['zona-premium', 'waterfront'],
      }),
      propiedades_ids: JSON.stringify([]),
      activo: true,
    },
    {
      tenant_id: tenantId,
      nombre: 'Para Entrega en 2028',
      slug: 'entrega-2028',
      configuracion: JSON.stringify({
        estado: 'en-construccion',
        año_entrega: 2028,
        tipo_proyecto: ['nuevo', 'pre-venta'],
      }),
      propiedades_ids: JSON.stringify([]),
      activo: true,
    },
    {
      tenant_id: tenantId,
      nombre: 'Inversión Rentable',
      slug: 'inversion-rentable',
      configuracion: JSON.stringify({
        intencion: 'inversion',
        rentabilidad_minima: 10,
        ubicacion_tipo: ['zona-comercial', 'zona-turistica'],
        precio_max: 300000,
      }),
      propiedades_ids: JSON.stringify([]),
      activo: true,
    },
    {
      tenant_id: tenantId,
      nombre: 'Primera Vivienda',
      slug: 'primera-vivienda',
      configuracion: JSON.stringify({
        intencion: 'compra',
        precio_max: 200000,
        tipo: ['apartamento', 'casa'],
        caracteristicas: ['financiamiento-disponible'],
        zonas: ['zona-residencial'],
      }),
      propiedades_ids: JSON.stringify([]),
      activo: true,
    },
    {
      tenant_id: tenantId,
      nombre: 'Zona Premium',
      slug: 'zona-premium',
      configuracion: JSON.stringify({
        zonas: ['puntacana', 'bavaro', 'casa-de-campo'],
        tipo: ['villa', 'penthouse', 'apartamento-lujo'],
        caracteristicas: ['vista-al-mar', 'acceso-playa'],
      }),
      propiedades_ids: JSON.stringify([]),
      activo: true,
    },
  ]);

  // 10. Textos Sueltos (6 bloques de texto/HTML)
  await knex('mock_textos_sueltos').insert([
    {
      tenant_id: tenantId,
      clave: 'hero_principal',
      titulo: 'Bienvenido a CLIC Inmobiliaria',
      contenido_html: '<h1>Encuentra tu Propiedad Ideal</h1><p>Somos especialistas en ayudarte a encontrar la propiedad perfecta para ti. Ya sea que busques comprar, vender o alquilar, estamos aquí para ayudarte.</p>',
      tipo: 'html',
      activo: true,
    },
    {
      tenant_id: tenantId,
      clave: 'about_description',
      titulo: 'Sobre Nosotros',
      contenido_html: '<p>CLIC Inmobiliaria es una empresa líder en el sector inmobiliario con más de 15 años de experiencia. Nos especializamos en propiedades residenciales, comerciales y de lujo.</p><p>Nuestro equipo de profesionales está comprometido con brindarte el mejor servicio y asesoría personalizada.</p>',
      tipo: 'html',
      activo: true,
    },
    {
      tenant_id: tenantId,
      clave: 'services_intro',
      titulo: 'Nuestros Servicios',
      contenido_html: '<p>Ofrecemos una amplia gama de servicios para satisfacer todas tus necesidades inmobiliarias:</p><ul><li>Compra y venta de propiedades</li><li>Alquileres residenciales y vacacionales</li><li>Gestión de propiedades</li><li>Asesoría en inversiones</li></ul>',
      tipo: 'html',
      activo: true,
    },
    {
      tenant_id: tenantId,
      clave: 'contact_cta',
      titulo: '¿Listo para Empezar?',
      contenido_html: '<h2>Contáctanos Hoy</h2><p>Nuestro equipo está listo para ayudarte a encontrar la propiedad de tus sueños. Agenda una consulta gratuita y descubre cómo podemos ayudarte.</p>',
      tipo: 'html',
      activo: true,
    },
    {
      tenant_id: tenantId,
      clave: 'footer_description',
      titulo: null,
      contenido_html: '<p>CLIC Inmobiliaria - Tu socio de confianza en bienes raíces desde 2009.</p>',
      tipo: 'text',
      activo: true,
    },
    {
      tenant_id: tenantId,
      clave: 'investment_benefits',
      titulo: 'Beneficios de Invertir',
      contenido_html: '<h3>¿Por qué invertir en bienes raíces?</h3><ul><li><strong>Rentabilidad:</strong> Genera ingresos pasivos constantes</li><li><strong>Seguridad:</strong> Inversión de bajo riesgo a largo plazo</li><li><strong>Valorización:</strong> El valor de la propiedad aumenta con el tiempo</li><li><strong>Diversificación:</strong> Diversifica tu portafolio de inversiones</li></ul>',
      tipo: 'html',
      activo: true,
    },
  ]);

  // 11. Asesores (8 asesores)
  await knex('mock_asesores').insert([
    {
      tenant_id: tenantId,
      nombre: 'Roberto',
      apellido: 'Martínez',
      cargo: 'Agente Inmobiliario Senior',
      biografia: 'Con más de 12 años de experiencia en el mercado inmobiliario, Roberto se especializa en propiedades residenciales de lujo y proyectos nuevos.',
      email: 'roberto.martinez@clic.com',
      telefono: '+1 809 555 0101',
      foto_url: 'https://i.pravatar.cc/300?img=11',
      redes_sociales: JSON.stringify({
        linkedin: 'https://linkedin.com/in/roberto-martinez',
        instagram: '@roberto_martinez_im',
      }),
      especialidades: JSON.stringify(['Propiedades de Lujo', 'Proyectos Nuevos', 'Ventas Residenciales']),
      experiencia_anos: 12,
      propiedades_vendidas: 245,
      logros: JSON.stringify([
        'Top Sales Agent 2023',
        'Mejor Agente de Lujo 2022',
        'Más de 200 propiedades vendidas',
      ]),
      activo: true,
      destacado: true,
      orden: 1,
    },
    {
      tenant_id: tenantId,
      nombre: 'María',
      apellido: 'González',
      cargo: 'Directora de Ventas',
      biografia: 'María lidera nuestro equipo de ventas y se especializa en propiedades comerciales e inversiones de alto valor.',
      email: 'maria.gonzalez@clic.com',
      telefono: '+1 809 555 0102',
      foto_url: 'https://i.pravatar.cc/300?img=20',
      redes_sociales: JSON.stringify({
        linkedin: 'https://linkedin.com/in/maria-gonzalez',
        twitter: '@maria_gonzalez_cl',
      }),
      especialidades: JSON.stringify(['Propiedades Comerciales', 'Inversiones', 'Consultoría']),
      experiencia_anos: 15,
      propiedades_vendidas: 312,
      logros: JSON.stringify([
        'Directora del Año 2023',
        'Líder en Ventas Comerciales',
        'Mentora de Nuevos Agentes',
      ]),
      activo: true,
      destacado: true,
      orden: 2,
    },
    {
      tenant_id: tenantId,
      nombre: 'Carlos',
      apellido: 'Rodríguez',
      cargo: 'Especialista en Alquileres',
      biografia: 'Carlos es experto en alquileres residenciales y vacacionales, ayudando a propietarios e inquilinos a encontrar la mejor opción.',
      email: 'carlos.rodriguez@clic.com',
      telefono: '+1 809 555 0103',
      foto_url: 'https://i.pravatar.cc/300?img=30',
      redes_sociales: JSON.stringify({
        linkedin: 'https://linkedin.com/in/carlos-rodriguez',
      }),
      especialidades: JSON.stringify(['Alquileres Residenciales', 'Alquileres Vacacionales', 'Gestión de Propiedades']),
      experiencia_anos: 8,
      propiedades_vendidas: 0,
      logros: JSON.stringify([
        'Especialista en Alquileres 2023',
        'Más de 500 alquileres gestionados',
      ]),
      activo: true,
      destacado: false,
      orden: 3,
    },
    {
      tenant_id: tenantId,
      nombre: 'Ana',
      apellido: 'Sánchez',
      cargo: 'Agente Inmobiliario',
      biografia: 'Ana se especializa en ayudar a familias jóvenes a encontrar su primera vivienda, con un enfoque en apartamentos y casas residenciales.',
      email: 'ana.sanchez@clic.com',
      telefono: '+1 809 555 0104',
      foto_url: 'https://i.pravatar.cc/300?img=47',
      redes_sociales: JSON.stringify({
        instagram: '@ana_sanchez_im',
      }),
      especialidades: JSON.stringify(['Primera Vivienda', 'Propiedades Residenciales', 'Financiamiento']),
      experiencia_anos: 6,
      propiedades_vendidas: 128,
      logros: JSON.stringify([
        'Top Agent Jóvenes Familias 2023',
        'Especialista en Financiamiento',
      ]),
      activo: true,
      destacado: false,
      orden: 4,
    },
    {
      tenant_id: tenantId,
      nombre: 'Luis',
      apellido: 'Hernández',
      cargo: 'Especialista en Proyectos Nuevos',
      biografia: 'Luis tiene una amplia experiencia en proyectos de pre-venta y desarrollos nuevos, ayudando a inversionistas y compradores a encontrar oportunidades.',
      email: 'luis.hernandez@clic.com',
      telefono: '+1 809 555 0105',
      foto_url: 'https://i.pravatar.cc/300?img=51',
      redes_sociales: JSON.stringify({
        linkedin: 'https://linkedin.com/in/luis-hernandez',
      }),
      especialidades: JSON.stringify(['Proyectos Nuevos', 'Pre-venta', 'Inversiones']),
      experiencia_anos: 10,
      propiedades_vendidas: 189,
      logros: JSON.stringify([
        'Especialista en Proyectos 2023',
        'Más de 50 proyectos gestionados',
      ]),
      activo: true,
      destacado: false,
      orden: 5,
    },
    {
      tenant_id: tenantId,
      nombre: 'Sofía',
      apellido: 'López',
      cargo: 'Agente de Lujo',
      biografia: 'Sofía se especializa exclusivamente en propiedades de lujo y alta gama, trabajando con clientes exigentes y propiedades premium.',
      email: 'sofia.lopez@clic.com',
      telefono: '+1 809 555 0106',
      foto_url: 'https://i.pravatar.cc/300?img=63',
      redes_sociales: JSON.stringify({
        linkedin: 'https://linkedin.com/in/sofia-lopez',
        instagram: '@sofia_lopez_luxury',
      }),
      especialidades: JSON.stringify(['Propiedades de Lujo', 'Penthouse', 'Villas Premium']),
      experiencia_anos: 9,
      propiedades_vendidas: 76,
      logros: JSON.stringify([
        'Agente de Lujo del Año 2023',
        'Especialista en Propiedades Premium',
      ]),
      activo: true,
      destacado: true,
      orden: 6,
    },
    {
      tenant_id: tenantId,
      nombre: 'Pedro',
      apellido: 'González',
      cargo: 'Consultor de Inversiones',
      biografia: 'Pedro ayuda a inversionistas a construir portafolios inmobiliarios rentables, analizando oportunidades y maximizando retornos.',
      email: 'pedro.gonzalez@clic.com',
      telefono: '+1 809 555 0107',
      foto_url: 'https://i.pravatar.cc/300?img=69',
      redes_sociales: JSON.stringify({
        linkedin: 'https://linkedin.com/in/pedro-gonzalez',
      }),
      especialidades: JSON.stringify(['Inversiones', 'Análisis de Mercado', 'Portafolios']),
      experiencia_anos: 11,
      propiedades_vendidas: 0,
      logros: JSON.stringify([
        'Consultor del Año 2023',
        'Más de 100 portafolios gestionados',
      ]),
      activo: true,
      destacado: false,
      orden: 7,
    },
    {
      tenant_id: tenantId,
      nombre: 'Isabel',
      apellido: 'Ramírez',
      cargo: 'Agente Inmobiliario',
      biografia: 'Isabel se especializa en propiedades turísticas y vacacionales, ayudando tanto a compradores como a propietarios en zonas costeras.',
      email: 'isabel.ramirez@clic.com',
      telefono: '+1 809 555 0108',
      foto_url: 'https://i.pravatar.cc/300?img=45',
      redes_sociales: JSON.stringify({
        instagram: '@isabel_ramirez_im',
      }),
      especialidades: JSON.stringify(['Propiedades Turísticas', 'Alquileres Vacacionales', 'Zonas Costeras']),
      experiencia_anos: 7,
      propiedades_vendidas: 94,
      logros: JSON.stringify([
        'Especialista en Turismo 2023',
      ]),
      activo: true,
      destacado: false,
      orden: 8,
    },
  ]);

  console.log('✅ Mock data seed completado exitosamente');
}

