import { Knex } from 'knex';

/**
 * Seed: Propiedades de ejemplo para Demo
 *
 * Crea propiedades de ejemplo para mostrar en la homepage del tenant demo.
 */

export async function seed(knex: Knex): Promise<void> {
  // Obtener el tenant demo
  const tenant = await knex('tenants').where('slug', 'demo').first();
  if (!tenant) {
    console.log('⚠️ No se encontró el tenant demo. Skipping seed.');
    return;
  }

  const tenantId = tenant.id;

  // Verificar si ya hay propiedades para este tenant
  const existingCount = await knex('propiedades').where('tenant_id', tenantId).count('id as count').first();
  if (existingCount && Number(existingCount.count) > 0) {
    console.log(`ℹ️ Ya existen ${existingCount.count} propiedades para el tenant demo. Skipping.`);
    return;
  }

  const propiedades = [
    {
      tenant_id: tenantId,
      titulo: 'Apartamento Moderno en Piantini',
      codigo: 'APT-001',
      descripcion: 'Hermoso apartamento de 3 habitaciones con vista panorámica a la ciudad. Acabados de primera, cocina moderna con isla, balcón amplio y 2 parqueos techados.',
      tipo: 'apartamento',
      operacion: 'venta',
      precio: 285000,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'Santo Domingo',
      ciudad: 'Santo Domingo',
      sector: 'Piantini',
      habitaciones: 3,
      banos: 2,
      medios_banos: 1,
      estacionamientos: 2,
      m2_construccion: 165,
      imagen_principal: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      ]),
      amenidades: JSON.stringify(['Gimnasio', 'Piscina', 'Seguridad 24/7', 'Lobby']),
      estado_propiedad: 'disponible',
      destacada: true,
      slug: 'apartamento-moderno-piantini',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Casa con Piscina en Arroyo Hondo',
      codigo: 'CASA-001',
      descripcion: 'Espectacular casa de 4 habitaciones con piscina privada, jardín amplio, terraza techada y área de BBQ. Ideal para familias.',
      tipo: 'casa',
      operacion: 'venta',
      precio: 450000,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'Santo Domingo',
      ciudad: 'Santo Domingo',
      sector: 'Arroyo Hondo',
      habitaciones: 4,
      banos: 3,
      medios_banos: 1,
      estacionamientos: 3,
      m2_construccion: 320,
      m2_terreno: 500,
      imagen_principal: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      ]),
      amenidades: JSON.stringify(['Piscina', 'Jardín', 'BBQ', 'Terraza', 'Seguridad']),
      estado_propiedad: 'disponible',
      destacada: true,
      slug: 'casa-piscina-arroyo-hondo',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Penthouse de Lujo en Naco',
      codigo: 'PH-001',
      descripcion: 'Exclusivo penthouse dúplex con terraza privada de 100m², jacuzzi, vista 360° a la ciudad. Acabados importados y domótica.',
      tipo: 'apartamento',
      operacion: 'venta',
      precio: 750000,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'Santo Domingo',
      ciudad: 'Santo Domingo',
      sector: 'Naco',
      habitaciones: 4,
      banos: 4,
      medios_banos: 1,
      estacionamientos: 3,
      m2_construccion: 450,
      imagen_principal: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800',
      ]),
      amenidades: JSON.stringify(['Terraza', 'Jacuzzi', 'Domótica', 'Gimnasio', 'Lobby VIP']),
      estado_propiedad: 'disponible',
      destacada: true,
      exclusiva: true,
      slug: 'penthouse-lujo-naco',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Apartamento Acogedor en Bella Vista',
      codigo: 'APT-002',
      descripcion: 'Cómodo apartamento de 2 habitaciones, perfecto para pareja o inversión. Cerca de plazas comerciales y transporte.',
      tipo: 'apartamento',
      operacion: 'venta',
      precio: 125000,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'Santo Domingo',
      ciudad: 'Santo Domingo',
      sector: 'Bella Vista',
      habitaciones: 2,
      banos: 2,
      estacionamientos: 1,
      m2_construccion: 95,
      imagen_principal: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
      ]),
      amenidades: JSON.stringify(['Seguridad 24/7', 'Lobby', 'Área social']),
      estado_propiedad: 'disponible',
      destacada: false,
      slug: 'apartamento-acogedor-bella-vista',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Villa Frente al Mar en Punta Cana',
      codigo: 'VILLA-001',
      descripcion: 'Impresionante villa de 5 habitaciones con acceso directo a la playa. Piscina infinity, casa de huéspedes y muelle privado.',
      tipo: 'casa',
      operacion: 'venta',
      precio: 2500000,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'La Altagracia',
      ciudad: 'Punta Cana',
      sector: 'Cap Cana',
      habitaciones: 5,
      banos: 6,
      medios_banos: 2,
      estacionamientos: 4,
      m2_construccion: 650,
      m2_terreno: 1200,
      imagen_principal: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
        'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      ]),
      amenidades: JSON.stringify(['Playa privada', 'Piscina infinity', 'Muelle', 'Casa de huéspedes', 'Gym']),
      estado_propiedad: 'disponible',
      destacada: true,
      exclusiva: true,
      slug: 'villa-frente-mar-punta-cana',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Apartamento para Alquiler en Gazcue',
      codigo: 'APT-003',
      descripcion: 'Acogedor apartamento amueblado de 1 habitación. Ideal para ejecutivos. Incluye agua, luz e internet.',
      tipo: 'apartamento',
      operacion: 'renta',
      precio: 850,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'Santo Domingo',
      ciudad: 'Santo Domingo',
      sector: 'Gazcue',
      habitaciones: 1,
      banos: 1,
      estacionamientos: 1,
      m2_construccion: 55,
      imagen_principal: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
        'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
      ]),
      amenidades: JSON.stringify(['Amueblado', 'Internet incluido', 'Servicios incluidos']),
      estado_propiedad: 'disponible',
      destacada: false,
      slug: 'apartamento-alquiler-gazcue',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Local Comercial en Blue Mall',
      codigo: 'LOCAL-001',
      descripcion: 'Excelente local comercial en la zona más exclusiva. Alto tráfico peatonal. Ideal para boutique o restaurante.',
      tipo: 'local',
      operacion: 'renta',
      precio: 5500,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'Santo Domingo',
      ciudad: 'Santo Domingo',
      sector: 'Piantini',
      m2_construccion: 120,
      imagen_principal: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800',
      ]),
      amenidades: JSON.stringify(['Aire acondicionado central', 'Seguridad', 'Estacionamiento clientes']),
      estado_propiedad: 'disponible',
      destacada: true,
      slug: 'local-comercial-blue-mall',
      activo: true,
    },
    {
      tenant_id: tenantId,
      titulo: 'Terreno en Jarabacoa',
      codigo: 'TERR-001',
      descripcion: 'Hermoso terreno de montaña con vista al valle. Perfecto para construir tu casa de campo o proyecto turístico.',
      tipo: 'terreno',
      operacion: 'venta',
      precio: 95000,
      moneda: 'USD',
      pais: 'República Dominicana',
      provincia: 'La Vega',
      ciudad: 'Jarabacoa',
      sector: 'La Confluencia',
      m2_terreno: 2500,
      imagen_principal: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      imagenes: JSON.stringify([
        'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
      ]),
      amenidades: JSON.stringify(['Vista al valle', 'Acceso pavimentado', 'Agua disponible', 'Electricidad cercana']),
      estado_propiedad: 'disponible',
      destacada: false,
      slug: 'terreno-jarabacoa',
      activo: true,
    },
  ];

  await knex('propiedades').insert(propiedades);
  console.log(`✅ Se insertaron ${propiedades.length} propiedades de ejemplo para el tenant demo.`);
}
